name: ci
on:
  push:
    branches:
      - master
    paths: 
      - "src/App.js"
  pull_request:
    branches:
      - master
    paths: 
      - "src/App.js"
  workflow_dispatch:  
jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: install dep
        run: npm install
      - name: run tests
        run: npm run test

 