name: ci
on:
  push:
    branches:
      - master
    paths: 
      - "/src/index.js"
  pull_request:
    branches:
      - master
    paths: 
      - "/src/index.js"
  workflow_dispatch:  
jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
           ~/.gradle/caches
           ~/.gradle/wrapper     
      - name: install dep
        run: npm install
      - name: run tests
        run: npm run test

 