name: Update content

on:
  push:
    branches:
      - master
    paths: 
      - "src/App.js"
  workflow_dispatch:
permissions:
  contents: write 
jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout master branch
       uses: actions/checkout@v4
       with:
         ref: master
    
     - name: sync changes
       run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git commit -m "sync all from master with via GitHub Actions"
           git push --force origin master:ovi-pages
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}