name: Update content

on:
  push:
    branches:
      - master
    paths: 
      - "src/App.js"
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
     - name: Clone Repository B
       uses: GuillaumeFalourd/clone-github-repo-action@v2.3
       with:
         depth: 1
         branch: 'master'
         owner: 'HasanAshab'
         repository: 'ovi-ci'

     - name: Access app js content
       run: |
         cd ovi-ci
         cd src
         cat App.js
       id: access_appjs_content
#          git config --global user.email "samertask@gmail.com"
#          git config --global user.name "HasanAshab"
#          git add App.js
#          git commit -m "Update sam.md"
     - name: Push to branch ovi pages
       run: echo steps.access_appjs_content.outputs

   # - name: Push to Repository B
    #  run: |
   #     cd b
    #    git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/iam-sameera/b.git
     #   git push