name: Update content

on:
  push:
    branches:
      - master
    paths: 
      - "src/App.js"
  workflow_dispatch:
permissions:
  contents: write 
jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout master branch
       uses: actions/checkout@v4
       with:
         ref: master
     - name: Access app js content
       run: |
         echo "content<<EOF" >> $GITHUB_ENV
         cat src/App.js >> $GITHUB_ENV
         echo "EOF" >> $GITHUB_ENV       
       id: access_appjs_content
 
     - name: Checkout ovi pages branch
       uses: actions/checkout@v4
       with:
         ref: "ovi-pages"
     
     - name: check past content
       run: cat src/App.js       
   
     - name: Commit and push changes
       run: |
           cd src
           rm -f App.js
           echo "lol" > App.js
           cat App.js
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git add App.js
           git commit -m "Update App.js via GitHub Actions"
           git push origin HEAD:ovi-pages
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}