name: Update content

on:
  push:
    branches:
      - master
    paths: 
      - "src/App.js"
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout master branch
       uses: actions/checkout@v4
       with:
         ref: master
     - name: Access app js content
       run: echo "file_content=$(cat src/App.js)" >> $GITHUB_ENV
       id: access_appjs_content
     - name: Push to branch ovi pages
       run: echo "$file_content"



   # - name: Push to Repository B
    #  run: |
   #     cd b
    #    git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/iam-sameera/b.git
     #   git push